AllCops:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'bin/ddg.rb'
    - 'spec/*/**'
    - 'vendor/*'
    - 'vendor/*/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# This allows classes without a top-level
# documentation comment
Style/Documentation:
  Enabled: false
